FROM node:22-alpine AS build
WORKDIR /app
RUN npm install -g pnpm@12
COPY . .
RUN pnpm install --frozen-lockfile --ignore-scripts && cd packages/client && pnpm build

FROM node:22-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/packages/client/dist ./dist
EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]