FROM node:22-alpine
RUN apk add --no-cache curl \
 && curl -sL https://github.com/rjarem/netspace/archive/refs/heads/master.tar.gz | tar xz --strip-components=1 -C /tmp \
 && npm install -g serve \
 && cp -r /tmp/packages/client/dist /app
WORKDIR /app
EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]